### ISSUE TITLE
阿里云地址带的 spm 参数

### ISSUE THREAD

**Issue by Cat7373** [dmscode/Link-cleaner#1]
建议增加阿里云的规则，去掉 Url 中的 spm，已知域名：home.console.aliyun.com、account.aliyun.com、yq.aliyun.com 等等，从 aliyun.com 随便点开点啥都会带着这个参数

**Comment by dmscode** [comment]
目前没有说明适配的网址都会被应用一个通用规则，尝试净化。这个规则是白名单制度，只保留了有限的几个 get 参数 `['id', 'tid', 'uid', 'q', 'wd', 'query', 'keyword']`。

所以，应该可以完成这个净化任务。毕竟我就是因为被阿里系烦的不行才写的这个，淘宝部分网址可以被净化掉 80%+ 的内容。

**Comment by Cat7373** [comment]
至少我在 Safari 上似乎并没起作用😂

**Comment by dmscode** [comment]
我这里是没有问题的，不过因为没有苹果设备 Safari 我没法测试。

简单判断一下，是否最新版本的脚本，0.0.4。点击按钮后是否弹出通知，页面是否刷新？

**Comment by Cat7373** [comment]
emmm 白名单感觉有点过，感觉可能会影响一些正常网页，然后可能会以为遇到诡异的 bug 并排查大半天，因此决定还是先禁了😂

**Comment by dmscode** [comment]
所以每次加了一个自动跳转，来验证这个网址的可用性。最常用的地方主要还是国内这几个大站，淘宝京东重灾区
