### ISSUE TITLE
只在支持的站点上生效

### ISSUE THREAD

**Issue by oscargong** [dmscode/Link-cleaner#2]
游猴脚本支持语法：
```
// @include     http*://*taobao.com/*
```
使脚本只在声明的站点上生效。

能否只声明支持的站点？

**Comment by dmscode** [comment]
这是一个取舍问题。

目前有一条通配规则，试图尽可能适配大多数网站，比如去掉不必要的参数，只保留重点参数。而且大多是我我们需要做净化也是这个原因。

那么，是否要保持这个通配呢？我个人觉得它可以解决我 50% 以上的问题，这就很有保留的必要了，反正那个小小的按钮也没有太大影响。

当然，我也不能要求每个人和我的情况都一致，尤其是暗色背景，可能真的很突兀。这时候有两个选择，一个是在需要的时候再开启这个脚本，毕竟常常的，我们的分享都是集中行为，比如双十一临近，这几天我都要和朋友分享商品，那就打开，平时关掉。

或者选择使用小书签，其实小书签体验挺好的，只是不方便跟踪更新，不过可以关注这边，又更新了手动更一下，反正，我更新也不频繁。

最后，其实写成浏览器扩展的体验是最好的，但是，我现在的卡过不了验证，上赶着给 Google 那五美刀都给不上，就十分的尴尬。
