### ISSUE TITLE
请问可以油猴加个开关吗？

### ISSUE THREAD

**Issue by f59375543** [dmscode/Link-cleaner#3]
可以让脚本在打开链接时就默认净化网址，这样我们的网址栏也看得舒服一点

**Comment by dmscode** [comment]
这是一个取舍问题。

* 尝试用通用的规则去适配尽可能多的网址，万一可以用，就对用户有一定的帮助。这是好的一方面；而坏的一方面是，这样的尽可能去适配，并不能够保证从不出错。如果打开链接即净化，将会把这些错误最大化的暴露出来。
* 最短可用，目标是用来分享。有些地址已经被精简到确实可以使用，但必然产生一定的跳转，而不会维持在当前状态之下，虽然页面依旧是正确的。此时对于分享是比较友好的，但是对于日常浏览不仅没有必要，而且增加运算负担，甚至可能导致死循环。

基于这些考虑，于是做成了现在这个样子。
