### ISSUE TITLE
按钮可以贴边隐藏或者移动或者在油候页面可以点击？

### ISSUE THREAD

**Issue by 2220209876** [dmscode/Link-cleaner#4]
![image](https://user-images.githubusercontent.com/7346652/80943205-3f90c400-8e19-11ea-9c74-2f7c6b2f6820.png)
一直在页面有点不美观
![image](https://user-images.githubusercontent.com/7346652/80943277-664efa80-8e19-11ea-84d7-1a9f73ab8fda.png)
在油候页面可以点击，比如这个h5插件这样的效果

**Comment by dmscode** [comment]
这个有兼容性和使用习惯方面的考虑。

不过，可以考虑再加上菜单。我争取最近更新一下。

感谢您的意见~

**Comment by dmscode** [comment]
菜单已添加~
