### ISSUE TITLE
请求适配微信公众号文章分享链接

### ISSUE THREAD

**Issue by chsbuffer** [dmscode/Link-cleaner#5]
Scripts/rules.js   
```
  'mp.weixin.qq.com':{ /* WeChat Official Accounts Platform */
    testReg: /^http(?:s)?:\/\/mp.weixin.qq.com\/s\?.*$/i,
    query: ['__biz','mid','idx','sn'],
  },
```

**Comment by dmscode** [comment]
首先抱歉，隔了这么久才看到这条消息。

然后感谢，连规则都写出来了，真的好评！

微信公众号最开始我就研究过的，结果发现哪个参数也无法去掉。十分尴尬。如你所写，要保留的参数不少，结果的长度依然不低。

而且这个规则并不完全可用，去搜狗的微信搜索里随便打开一篇文章，地址是完全可以通过验证的，但是不包含上述任何一个参数，再次尴尬。

微信公众号内容是有短地址的，比如通过微信电脑客户端打开公众号内容，然后选择浏览器打开，地址就比较短小舒适。但是转换规则未知，就难以适配。
