### ISSUE TITLE
Greasy Fork 链接净化相关建议

### ISSUE THREAD

**Issue by Geeyun-JY3** [dmscode/Link-cleaner#6]
1. 建议去除任意 Greasy Fork 页面 URL 中的语言参数，如脚本页净化成 `https://greasyfork.org/scripts/373270`，见 Greasy Fork 站长对这条讨论的 [回复](https://greasyfork.org/discussions/greasyfork/57688#comment-149802)；
2. 建议将用户页 URL 中的用户名参数去除，即像脚本页净化结果一样去除 `-用户名` 变成 `https://greasyfork.org/users/*****`
3. 目前某脚本讨论（discussions）和讨论下具体某一条评论（comment）链接净化后会变成该脚本页，建议适配 Greasy Fork 新版脚本讨论和评论 URL 进行净化；类似的，Script Sets 页会净化成 `https://greasyfork.org/scripts`;

**Comment by dmscode** [comment]
收到，全部接受。会在近期处理。十分感谢建议~

（卖个萌，喵~

**Comment by Geeyun-JY3** [comment]
建议顺便也把 README、主页等地方的 Greasy Fork 链接也去除语言参数，缩短至上述最短可用状态

**Comment by dmscode** [comment]
这个接受，今天开始处理。

我得先把代码合并工具重新整理一下，可能需要点时间。

**Comment by dmscode** [comment]
At v0.1.4
- [x] GreasyFork 净化后会去除语言参数。
- [x] 新增对讨论页（保留锚点，可定位到具体楼层），用户页的净化
- [x] 脚本说明页的 GreasyFork 地址去除语言参数。

**Comment by Geeyun-JY3** [comment]
我这边测试讨论页定位到具体楼层（评论）还是会被清除
***
补加一条建议，建议对脚本页下任意 tab 的链接都进行净化，包括 `代码（code）` `历史版本（versions）` ` 反馈（feedback）` `统计数据（stats）`，净化成形如 `https://greasyfork.org/scripts/373270/****`

**Comment by dmscode** [comment]
加上了，粗略适配，不是很完善，但是常用标签应该都有了。

At v0.1.5

**Comment by Geeyun-JY3** [comment]
再补充一个，Greasy Fork 论坛中除脚本讨论以外的其他讨论的链接格式和脚本讨论页的是不太一样的，如 `https://greasyfork.org/zh-CN/discussions/greasyfork/57688-greasy-fork-url-without-language-code-en-ja-zh-cn-etc`，也请求把这个适配了（抱歉我应该一次性提完的🤦‍♂️）

**Comment by dmscode** [comment]
> 抱歉我应该一次性提完的

这个不用抱歉，毕竟……我也不可能一次把脚本写完美不是~

昨天看了一眼论坛的，然后偷懒了。现在你把问题提炼出来，我就省的动脑整理了。（偷懒得逞的欣喜~

晚一点去搞定它。（GreasyFork 的规则稍微多了点，已经陷入要权衡规则先后顺序的情况了，喵叽~

**Comment by Geeyun-JY3** [comment]
对 Greasy Fork 的适配做到这个程度已经可以说是深度适配了😄

**Comment by dmscode** [comment]
> 可以说是深度适配了

是的（日常宠粉 😋

**Comment by dmscode** [comment]
搞定了 At v0.1.7

发布时手残同步到其他脚本上去了，搞得一通乱七八糟，呜呜呜

**Comment by Geeyun-JY3** [comment]
辛苦了。
大致测试了一下，除了 Script Sets 应该都没问题了。如果没收到相关反馈这三个 issue 你就看着关吧。

**Comment by dmscode** [comment]
别客气，感谢反馈，我先都关掉，有问题再开新反馈嗷~

**Comment by Geeyun-JY3** [comment]
嗯？等等 Script Sets 页是不是还没适配？

**Comment by dmscode** [comment]
> Script Sets 页

原来还存在着这么一个地方，喵喵喵~下午搞定吧。

（讲真，GreasyFork 我并不熟悉，要不是这一段那边老有人喵喵喵我，我连这网站的名字都记不住怎么拼写那种……所以丢掉几个位置没适配什么的，就情有可原嗷~

**Comment by dmscode** [comment]
搞定了，顺便支持了脚本列表的页数。（不过过滤器依然会被删除

At v0.1.8

**Comment by Geeyun-JY3** [comment]
测试了下，0.1.8 和以前版本的区别好像就只是不会再跳转至 `https://greasyfork.org/scripts`，但是净化了个寂寞，确认适配的是形如 `https://greasyfork.org/<language>/scripts?set=***` 的 Script Sets 页？

**Comment by dmscode** [comment]
应该是吧，一会儿我再去检查一下规则

**Comment by dmscode** [comment]
这种情况无法去掉语言字段，这是主函数的锅，我当时没考虑这么复杂的情况。暂时懒得修改。

**Comment by Geeyun-JY3** [comment]
> 这种情况无法去掉语言字段，这是主函数的锅，我当时没考虑这么复杂的情况。暂时懒得修改。

好的吧

**Comment by Geeyun-JY3** [comment]
偶然发现 Firefox 扩展页也有和这里说的 Greasy Fork 的第一点类似，都可以去掉语言参数（甚至可以直接把 `zh-CN/firefox/` 去掉，如 `https://addons.mozilla.org/zh-CN/firefox/addon/trello-improvements/` 可以净化成 `https://addons.mozilla.org/addon/trello-improvements/`。
PS：我不用 Firefox，纯粹偶然发现🌚

**Comment by dmscode** [comment]
语言参数暂时不做太多处理吧，一方面确实不太好弄，另一方面分享时未必不希望保留语言参数，有些网站可能默认英文等。

**Comment by Geeyun-JY3** [comment]
> 语言参数暂时不做太多处理吧，一方面确实不太好弄，另一方面分享时未必不希望保留语言参数，有些网站可能默认英文等。

那为啥一开始肯给 Greasy Fork 做适配，感觉是类似的呀🌚

**Comment by dmscode** [comment]
最开始没走脑子，你提了我就弄了。后来发现这种情况太普遍，这么处理不太好，但还没想出什么好办法，嗷叽

**Comment by Geeyun-JY3** [comment]
> 最开始没走脑子，你提了我就弄了。后来发现这种情况太普遍，这么处理不太好，但还没想出什么好办法，嗷叽

啊这，什么意思啊🌚？是指一个一个网站适配太累了？想找一个适用性较强的实现方式？

**Comment by dmscode** [comment]
有点这样的想法，但是这一块挺不好弄的。头疼，暂缓吧（无限期拖延

还有个原因是用正则识别并不能保证完全无误，就有可能出问题，这样为了短而引入更多问题也不太值得。

**Comment by Geeyun-JY3** [comment]
好的吧

**Comment by dmscode** [comment]
最近（其实一直都是） idea 比较多，得先安静填填坑，待办列表要炸系列。
