### ISSUE TITLE
App Store 净化相关建议

### ISSUE THREAD

**Issue by Geeyun-JY3** [dmscode/Link-cleaner#7]
1. 建议加个判断逻辑自动匹配所地区，当链接非用户所在地区时净化后的链接变为用户所在地区；
2. 建议净化后的链接可以去除应用名称，只保留应用 id（？），即 `https://apps.apple.com/cn/app/id******`。

**Comment by dmscode** [comment]
自动匹配地区这个有难度，最近有在思考一个类似的功能，但是挺头疼的。首先语音（区域）的标记有几种格式，还涉及到大小写，各个网站采用的方案不同，没法统一处理，然后网站提供的语言（区域）支持也可能不是完整的。简言之，情况很复杂，需要对单个网站做大量适配工作。所以现在就只针对中国区域优化，比如 App Store 会直接转换为 cn 区域。

App Store 的网址应该是会被净化到 `https://apps.apple.com/cn/app/id******`，如果有页面未被正确净化，请报告给我，我再进行适配。

**Comment by Geeyun-JY3** [comment]
> App Store 的网址应该是会被净化到 `https://apps.apple.com/cn/app/id******`，如果有页面未被正确净化，请报告给我，我再进行适配。

随便找了两个应用试了下都不行啊，如：https://apps.apple.com/cn/app/moneywiz-2-personal-finance/id936248215 https://apps.apple.com/cn/app/%E4%B8%93%E4%B8%9A%E8%AE%B0%E8%B4%A6%E5%8A%A9%E6%89%8Bmoney-pro-%E5%AE%B6%E5%BA%AD%E5%8F%8A%E4%B8%AA%E4%BA%BA%E7%90%86%E8%B4%A2%E4%B8%80%E7%AB%99%E5%BC%8F%E8%A7%A3%E5%86%B3/id918609651

**Comment by dmscode** [comment]
> 随便找了两个应用试了下都不行

确实，下次一并修复

**Comment by Geeyun-JY3** [comment]
> 比如 App Store 会直接转换为 cn 区域

测试了一下好像有问题啊，像打开美区的 https://apps.apple.com/us/app/moneywiz-3-personal-finance/id1004710719 后是个 404 页，点击脚本管理器工具栏图标后的菜单也无脚本菜单。

**Comment by dmscode** [comment]
> 好像有问题

收到~

**Comment by dmscode** [comment]
以前适配的是 `itunes.apple.com` 的地址，而现在变成了 `apps.apple.com`，所以出现无法净化的问题，现在两个地址都兼容了。

At v0.1.4

**Comment by dmscode** [comment]
噢，对了，净化后的区域还是会设置为 `cn`，因为不加区域会出错，依然先满足国内用户的需求。（毕竟我写软件介绍啥的时候也需要这样的链接，2333

**Comment by Geeyun-JY3** [comment]
我没有使用过任何苹果设备，关于 App Store 的这个链接基本是完全不了解🤣。我也试过去找 App Store 有没有像 Microsoft Store 一样 #8 提到的可以根据用户所在地区或使用语言自动跳转的网址格式，没找到。不知道苹果的开发者文档有没相关内容。
***
另外刚刚测试了下 0.1.4 好像有问题，复制出来的链接是 `https://www.microsoft.com/store/apps/app/id*******`，这是不是和 Microsoft Store 写混了🌚。

**Comment by dmscode** [comment]
> 是不是和 Microsoft Store 写混了

是的，修改了。
