### ISSUE TITLE
Microsoft Store 链接净化相关建议

### ISSUE THREAD

**Issue by Geeyun-JY3** [dmscode/Link-cleaner#8]
Microsoft Store 的应用链接的最短可用状态其实是 `https://www.microsoft.com/store/apps/<app's Store ID>`（可参考 [官方文档](https://docs.microsoft.com/windows/uwp/publish/link-to-your-app)），比目前净化的结果还要短，还能根据用户地区语言跳转至相应的 `https://www.microsoft.com/**/p/<app's name>/<app's Store ID>`。
就是不知道这种对链接改动相对较大的「净化」考虑做吗？

**Comment by dmscode** [comment]
我一会儿看一下，只要是网站提供的合理缩短的地址（刻意转换的短地址除外），我都接受。

问题是有一些难以在页面中直接稳定获取，比如微信公众号内容，我知道有一个短的形式，但是在页面中难以获取，就一直无奈中。

**Comment by Geeyun-JY3** [comment]
> 我一会儿看一下，只要是网站提供的合理缩短的地址（刻意转换的短地址除外），我都接受。
> 
> 问题是有一些难以在页面中直接稳定获取，比如微信公众号内容，我知道有一个短的形式，但是在页面中难以获取，就一直无奈中。

某种意义上确实可以说 Microsoft Store 应用链接和微信公众号内容链接是类似的，ta们都有一个更短的形式，区别是 Microsoft Store 应用链接的更短形式的格式是已知的，相对微信的也更容易转换得到

**Comment by dmscode** [comment]
以前没有 Microsoft Store 的规则，现在加上了，目前 <app's Store ID> 按照 12 位小写字母加数字的规则获取，希望微软不要乱改。

At v0.1.4

**Comment by Geeyun-JY3** [comment]
测试了下 0.1.4，好像有些问题：
比如点击 `https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp` 后等页面加载完成后链接会变为 `https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp?activetab=pivot:overviewtab`, 净化后的链接是 `https://www.microsoft.com/store/apps/9nblggh516xpactivetab=pivot:overviewtab`，跳转会报错。

概括的说就是链接还是 `https://www.microsoft.com/**/p/<app's name>/<app's Store ID>` 的时候复制出来的净化链接没问题，但如果后面还有别的参数复制出来的净化链接可能是有问题的。

**Comment by dmscode** [comment]
> 好像有些问题

测试几次，没有复现，看规则也不应该出现这样的问题，请再测试一下。

**Comment by Geeyun-JY3** [comment]
> 测试几次，没有复现，看规则也不应该出现这样的问题，请再测试一下。

还是有，其实就是对形如 `https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp?activetab=pivot:overviewtab` 的网址净化有问题，净化后的结果是 `https://www.microsoft.com/store/apps/9nblggh516xpactivetab=pivot:overviewtab`，进而跳转报错。

**Comment by dmscode** [comment]
> 还是有

好的，我这里重现了，一会琢磨一下

**Comment by dmscode** [comment]
老也没动这个脚本，现在写相关正则就丢三落四的，果然写丢了一种情况，搞定了。

At v0.1.6 （等一会儿更新过去

**Comment by Geeyun-JY3** [comment]
等会还有个问题，是哔哩哔哩的 UP 主视频频道的，懒得再开一个 issue 了，直接上例子：`https://space.bilibili.com/546195/channel/detail?cid=42104`，净化后会把最后的 `?cid=42104` 清除掉；类似的还有收藏夹。
b 站相关参数的清理可以参考 [Bilibili Evolved](https://github.com/the1812/Bilibili-Evolved) 的 `网址参数清理` 功能

**Comment by dmscode** [comment]
这类问题算是已知。

Greasy Fork 的链接问题也类似。（区域设置可以去掉这个是我没想到的）

只适配了主要问题，没做深度适配。因为深度适配太复杂了，要考虑的情况非常多，稳定性也会降低。所以主要解决关键的点，比如分享某个脚本，分享某个视频，分享某个 Up 等。而没做更细致的适配。

类似的还有，对搜索结果进行净化后会去掉各种过滤条件，只剩下在哪个网站搜索什么内容这样的关键信息。如果逐参数筛选是否有必要保留，复杂度会成几何倍数增加。就太难以维护了。

**Comment by Geeyun-JY3** [comment]
嗯可以理解，做起深度适配确实吃力，而且网站一改就又要重新适配。

**Comment by dmscode** [comment]
> 而且网站一改就又要重新适配。

越是复杂，越容易失效。书写的复杂度也非常高，甚至规则的先后顺序都要反复推敲。

所以，再找到更好的方法之前，大概不会考虑深度适配。（我自己特别感兴趣的内容除外，2333

**Comment by Geeyun-JY3** [comment]
> 目前 <app's Store ID> 按照 12 位小写字母加数字的规则获取

我看几个开发者用标准的商店链接都是大写字母，带语言地区的链接倒才是小写字母，要不再给换成大写🙈……~~（虽然都能用）~~

**Comment by dmscode** [comment]
> 几个开发者用标准的商店链接都是大写字母

我看看回头加上大写的兼容

**Comment by dmscode** [comment]
加上大写字母的兼容了

At v0.1.9

**Comment by Geeyun-JY3** [comment]
> 加上大写字母的兼容了

emmm我的意思是让复制出来的链接的 <app's Store ID> 中的字母都为大写字母
而且刚刚顺手又测试了三个链接发现些问题，好像如果链接中有中文无法净化至上述最短格式，如 [哔哩哔哩UWP](https://www.microsoft.com/zh-cn/p/哔哩哔哩uwp-第三方/9n7c87236453)、[RSS 追踪](https://www.microsoft.com/zh-cn/p/rss-追踪/9n85pv1rjd6v)，净化出来的结果分别是 `https://www.microsoft.com/zh-cn/p/哔哩哔哩uwp-第三方/9n7c87236453`和`https://www.microsoft.com/zh-cn/p/rss-追踪/9n85pv1rjd6v`

**Comment by dmscode** [comment]
修改了，希望有效

At v0.1.10
