### ISSUE TITLE
Trello 看板与卡片链接净化建议

### ISSUE THREAD

**Issue by Geeyun-JY3** [dmscode/Link-cleaner#9]
打开分享的 Trello 的看板和卡片的链接会在最后加上看板和卡片的标题，如 `https://trello.com/b/ud59t1fL` 打开后是 `https://trello.com/b/ud59t1fL/trello-android-app`，`https://trello.com/c/BvTUOwCk` 打开后是 `https://trello.com/c/BvTUOwCk/508-dark-mode`，建议把链接中的标题净化掉 ~~（虽然官方其实都有提供相应的 `链接到看板／卡片` 来这一获取该短链接）~~。

**Comment by dmscode** [comment]
加上了，没测试

At v0.1.10

**Comment by Geeyun-JY3** [comment]
又漏了东西🤦‍♂️，卡片上的评论也是和 Greasy Fork 类似，评论格式为`https://trello.com/c/Zn5qck13/60-night-mode#comment-5f4c93f076d3cb3ccbed7f2b`。
另外 GitHub 和 Greasy Fork 上都没看到 0.1.10 的更新。

**Comment by dmscode** [comment]
可能……我忘了提交了，一会修改了一并提交，喵叽
